### PR TITLE
Docker support with OpenCL

### PR DESCRIPTION
**Pull request by DaniAsh551**
Added docker support for the project.

The procedure to add support for different vendors differ, so I have added support for just nvidia as I have a nvidia GPU.

Would love to add support for intel and amd aswell.

You would need some pre-requisites to get this up and running, read more about OpenCL in docker [here](https://linuxhandbook.com/setup-opencl-linux-docker/).

### CODE REVIEW

**Comment by Noeda** [comment]
Oh hey, thanks! I tried to think how to add Dockerfile before but I got unhappy there wasn't a rustup-less version to get nightly Rust in a Dockerfile (with the idea that maybe the Dockerfile could not depend too much on constantly changing Rust compiler).

But in hindsight, I think as long as `rllama` requires nightly Rust there's not much way around that.

I'll be merging this today or over the weekend. I'll just run a test myself and then we are good to go. 👍

**Comment by Noeda** [comment]
I merged your code but I had to make some changes:

* It turns out it's a pain in the arse to get NVidia OpenCL actually expose the GPUs to the Docker container. I was working through testing the `Dockerfile` and noticed it can't list or use the GPU OpenCL devices. Some Internet searches later it seems that you need some custom NVidia packages to get GPUs exposed inside Dockerfiles, with said packages not in my Linux repositories (I use Fedora Linux) and that's when I gave up.

* I stripped out the OpenCL bits because of that so the Dockerfile is CPU only now (also renamed to `.docker/cpu` to reflect this).

* I documented the Dockerfile to README.md

The CPU-only Dockerfile is better than no Dockerfile at all. We may need to revisit how to get NVidia OpenCL to not be very complicated in Docker; if you are willing to work on it I'll review and merge if it makes using `rllama` easier.

**Comment by DaniAsh551** [comment]
Hey @Noeda 

First off, really appreciate you doing this as a hobby.

I am also on Fedora and in the merge request I mentioned the fact that some prerequisites are required and linked to an article describing those. But I think I should have added the instructions to the README aswell, sorry.

I tested this on my system, got it to a properly working state and pushed afterwards.

Should I re-open another request with the proper instructions again?

**Comment by Noeda** [comment]
If are willing to spend time on it, then go ahead and you can post a new PR or just comment here. Makes no difference to me.

And yeah, proper instructions would help. You can link to the OpenCL manual from the README.md in case it would get really long.

One thing that's missing from your `Dockerfile` that I forgot comment on: you need to enable `opencl` feature or it will just use regular CPU. `--features server,opencl`.

**Comment by DaniAsh551** [comment]
Okay, got it, will reopen another one

Also, should the instructions be a seperate md file? As in the future if AMD and intel instructions are also added, this would make the main README.md very long?

**Pull request merged**
