### PR TITLE
Add interactive mode in cli

### PR DESCRIPTION
**Pull request by kazord**
Thx for all the work already done.

My little contribution for your 'long term goal' of chatbot:
I added --interactive-stop
and --start-interactive

most of things tested with the chat prompt
 --prompt "A dialog, where Human interacts with AI. AI is helpful, kind, obedient, honest, and knows its own limits. Human: Hello, AI. AI: Hello! How can I assist you today? Human:" --interactive-stop Human:

### CODE REVIEW

**Comment by Noeda** [comment]
Howdy. I'm preparing to merge this, with some minor style modifications and README.md documentation (https://github.com/Noeda/rllama/compare/master...pr-3) but I have one question:

What is the purpose of the `--interactive-stop` switch? From what I can read from code, if the model outputs the `[EOF]` token sequence, then interactive mode resumes and you can type in another prompt? Is `[EOF]` something the interactive models tend to output?

I will merge once I test that the code is functional and maybe add some visual indication that the program is expecting you to type.

**Comment by kazord** [comment]
[EOF] is a unexpected default value, maybe i should have go for </s> instead ?
i wasn't really good with my explaination :)
--interactive-stop make the cli stop on specifique token, currently not handling new line well (maybe something with \cr\lf ?)
--start-interactive stop after the prompt compute, in order to add more prompt (will be usefull if we can save that compute).

For some math reason (above my level) after the initial forward, it need to forward word by word if you know why ?

**Comment by Noeda** [comment]
> [EOF] is a unexpected default value, maybe i should have go for instead ?

I think it's not an issue (I left it at `[EOF]`) There's not really a good default value anyway, it would depend on the prompt. Maybe once we get a model that's specifically instruct-tuned we can use a default or just engineer this in a way that works properly with such a model. I documented this in `README.md`.

> For some math reason (above my level) after the initial forward, it need to forward word by word if you know why ?

There's a thing called key-value cache, a collection of tensors used in attention that need to update after seeing every token. The way it's currently written it's possible to give all tokens at once (this is what's done for initial prompt) but it's not much faster than just giving it the tokens one by one in the current implementation like you wrote. So I didn't bother doing anything about that.

I also added `--interactive-prompt-postfix` which is a string that's appended automatically to the user typed string. I think you would add something like `AI: ` to it. It forces the AI to respond rather than try "continue" the user's question. So you can have command line like:

```
 rllama --f16 \
        --param-path /LLaMA/7B/params.json \
        --model-path /LLaMA/7B \
        --tokenizer-path /stonks/LLaMA/tokenizer.model \
        --prompt "This is an interactive session between human and AI assistant. AI: Hi! How can I help you? Human:" \
        --start-interactive \
        --interactive-stop "Human:" \
        --interactive-prompt-postfix " AI:"
```

**Comment by Noeda** [comment]
Look like we got good timing on this as a new instruct-finetuned model "Vicuna" came out recently: https://github.com/lm-sys/FastChat/

I'm going to work on making Vicuna work on this code and then adjust the defaults for that model specifically.

**Pull request merged**
